name: Deploy to SIT server

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: dev

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Run lint, test, cov ...
        run: |
          yarn install
          yarn run build:sit
          echo "lint, test, cov ..."
          echo "ok"

      - name: Deploy to SIT server
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY_RAKSMART}}
        with:
          flags: '-avz --delete'
          options: ''
          ssh_options: ''
          src: 'dist'
          dest: '${{ secrets.USER_RAKSMART }}@${{ secrets.HOST_RAKSMART }}:${{ secrets.DEST_DIR_SIT }}'

      - name: Run shell commands
        uses: appleboy/ssh-action@master
        env:
          DEST_DIR_SIT: ${{ secrets.DEST_DIR_SIT }}
        with:
          host: ${{ secrets.HOST_RAKSMART }}
          username: ${{ secrets.USER_RAKSMART }}
          key: ${{ secrets.DEPLOY_KEY_RAKSMART }}
          envs: DEST_DIR_SIT
          timeout: 60s
          proxy_timeout: 60s
          debug: true
          script: |
            cd "$DEST_DIR_SIT"/../
            bash ./deploy.sh
