name: Deploy to SIT server

on:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: dev

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Run lint, test, cov ...
        run: |
          yarn install
          yarn run build:sit
          echo "lint, test, cov ..."
          echo "ok"

      - name: Deploy to SIT server
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.tencentcloud_DEPLOY_KEY}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: 'dist'
          dest: '${{ secrets.tencentcloud_USERNAME }}@${{ secrets.tencentcloud_HOST }}:./yumecoder/portal/sit/temp'

      - name: Run shell commands
        uses: appleboy/ssh-action@master
        env:
          TC_USERNAME: ${{ secrets.tencentcloud_USERNAME }}
        with:
          host: ${{ secrets.tencentcloud_HOST }}
          username: ${{ secrets.tencentcloud_USERNAME }}
          key: ${{ secrets.tencentcloud_DEPLOY_KEY }}
          envs: TC_USERNAME
          script: |
            cd /home/$TC_USERNAME/yumecoder/portal/sit
            ./deploy.sh
