name: Deploy to SIT server

on:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: dev

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Run lint, test, cov ...
        run: |
          yarn install
          yarn run build:sit
          echo "lint, test, cov ..."
          echo "ok"

      - name: Deploy to SIT server
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY_CLOUDCONE}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: 'dist'
          dest: '${{ secrets.USER_CLOUDCONE }}@${{ secrets.HOST_CLOUDCONE }}:./yumecoder/portal/sit/temp'

      - name: Run shell commands
        uses: appleboy/ssh-action@master
        env:
          USER: ${{ secrets.USER_CLOUDCONE }}
        with:
          host: ${{ secrets.HOST_CLOUDCONE }}
          username: ${{ secrets.USER_CLOUDCONE }}
          key: ${{ secrets.DEPLOY_KEY_CLOUDCONE }}
          envs: USER
          timeout: 60s
          proxy_timeout: 60s
          debug: true
          script: |
            cd /home/$USER/yumecoder/portal/sit
            ./deploy.sh
